### ISSUE TITLE
Сделать метод по рекурсивному удаления файлов - аналог УдалитьФайлы только с флагом поиска в подкаталогах

### ISSUE THREAD

**Issue by artbear** [oscript-library/files-common#11]
/cc @nixel2007

**Comment by EvilBeaver** [comment]
УдалитьФайлы и так удаляет рекурсивно, если указан каталог. Или речь идет об удалении по маске внутри дерева каталогов?

**Comment by nixel2007** [comment]
@EvilBeaver да, именно удаление файлов по маске.
