### ISSUE TITLE
Процедура создания каталога, если его нет

### ISSUE THREAD

**Issue by nixel2007** [oscript-library/files-common#2]
Хочу реальную функцию ОбеспечитьКаталог, которая будет просто проверять его существование и создавать в случае его отсутствия. Без удаления файлов

**Comment by EvilBeaver** [comment]
А сейчас не так? Надо две функции. Обеспечить и обеспечить пустой.

**Comment by nixel2007** [comment]
Сейчас не так - оно грохает файлы. Вот под вторую функцию я и завёл ишуз
