### ISSUE TITLE
ОбъединитьПути превращает абсолютный каталог Linux в отностительный

### ISSUE THREAD

**Issue by KrapivinAndrey** [oscript-library/files-common#21]
![image](https://user-images.githubusercontent.com/586025/191416175-dc331fb3-42b3-4ebc-bc30-080c83935494.png)

**Comment by EvilBeaver** [comment]
А можно кусочек кода, как используется ОбъединитьПути?

**Comment by KrapivinAndrey** [comment]
Уже убрал. Но согласно скрину было что-то вроде:

ФС.ОбъединитьПути(ВремКаталог, "src/Мутанты/ПрерываниеЦиклов.os")

ВремКаталог виден в отладке.

В результате объединения путей теряется ведущий слеш

**Comment by KrapivinAndrey** [comment]
Посмотрел код - скорее всего из-за этого 

https://github.com/oscript-library/fs/blob/develop/%D0%9C%D0%BE%D0%B4%D1%83%D0%BB%D0%B8/%D0%A4%D0%A1.os#L263

Сначала разбираем путь на составляющие, потом делаем СтрСоединить. Это убьет ведущий разделитель

**Comment by nixel2007** [comment]
@KrapivinAndrey

Непонятно. Какой ведущий слеш? Где?

**Comment by KrapivinAndrey** [comment]
@nixel2007 

Вот добавил падающий тест. Но починить не получается

https://github.com/KrapivinAndrey/fs/blob/b2c9cc1f0f75c0ca9c8eabc86c1916425f097f42/tests/%D0%9F%D1%83%D1%82%D0%B8.os#L104

Думал проблема в СтрРазделить....

**Comment by nixel2007** [comment]
Так нельзя. Лидирующий слеш всегда считается за корень диска. Нужно исправлять вызывающий код

**Comment by KrapivinAndrey** [comment]
Так. Стало совсем не понятно. Я почти уверен что проблема была в СтрРазделить(...., Ложь).

Перенес этот код в 1с. В итога - да: это решает проблему


![image](https://user-images.githubusercontent.com/586025/192154436-a23d647e-6efe-490d-ae70-0cd5f179eec1.png)


В OS - пофиг истина или не истина в СтрРазделить

**Comment by KrapivinAndrey** [comment]
> исправлять

Так это ФС.ОбъединитьПути(ПолучитьВременныйКаталог(), чтотонужное)

**Comment by KrapivinAndrey** [comment]
Вот отсюда логика.

[Получить врем. каталог](https://github.com/KrapivinAndrey/mutagen/blob/main/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9A%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%B0%D0%97%D0%B0%D0%BF%D1%83%D1%81%D0%BA%D0%B0%D0%9C%D1%83%D1%82%D0%B0%D1%86%D0%B8%D0%B9.os#L92)

[Скопировать туда что-то полезное](https://github.com/KrapivinAndrey/mutagen/blob/main/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9A%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%B0%D0%97%D0%B0%D0%BF%D1%83%D1%81%D0%BA%D0%B0%D0%9C%D1%83%D1%82%D0%B0%D1%86%D0%B8%D0%B9.os#L95)

[Скопировать точечно файл](https://github.com/KrapivinAndrey/mutagen/blob/main/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9A%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%B0%D0%97%D0%B0%D0%BF%D1%83%D1%81%D0%BA%D0%B0%D0%9C%D1%83%D1%82%D0%B0%D1%86%D0%B8%D0%B9.os#L98)

В последнем было ОбъеднитьПути. И под windows все работало, а на GitHub Action - ломалось

**Comment by EvilBeaver** [comment]
@KrapivinAndrey опять ничего не понятно... Можешь, как для тупых вот прям написать: делаю вот это, получаю А, а ожидаю - Б?

**Comment by KrapivinAndrey** [comment]
https://github.com/oscript-library/fs/issues/21#issuecomment-1257228635

Вот тут ссылка на падающий тест

**Comment by KrapivinAndrey** [comment]
Небольшое исследование ФС.ОбъединитьПуть - работает некорректно. 
Просто метод ОбъединитьПути - нормально. 

Наверно надо просто удалить тогда ФС.ОбъединитьПути

**Comment by EvilBeaver** [comment]
@artbear а не ты ли делал поведение ФС.ОбъединитьПути специально отличным от просто ОбъединитьПути?

**Comment by EvilBeaver** [comment]
Ну точно: https://github.com/oscript-library/fs/blame/5fdfd2ce8b8048da03ecb519bce009601f85c9cb/tests/%D0%9F%D1%83%D1%82%D0%B8.os#L93

@KrapivinAndrey обрати внимание на название теста. ФС объединяет **правильно**. Это движок - неправильно

**Comment by nixel2007** [comment]
> Это движок - неправильно

что очень спорно

**Comment by EvilBeaver** [comment]
Нельзя спорить с @artbear. Можно только дать ему закодить метод с кошерным названием в библиотеке ФС

**Comment by KrapivinAndrey** [comment]
короч.. я у себя починил. ишуз тогда закрою. но тест у себя оставлю

**Comment by EvilBeaver** [comment]
Да, полагаю, что тем, кому надо поведение, как у Артура (аналог СтрСоединить) - можно пользоваться ФС, кому надо как надо - пользоваться системным методом. В данном случае, это не баг либы FS т.к. сделано намеренно именно так.
