### ISSUE TITLE
Имя библиотеки

### ISSUE THREAD

**Issue by nixel2007** [oscript-library/files-common#4]
В других языках похожие библиотеки называются fs. Как насчет переименования, пока не поздно? 
В fs или в fs-common. 
Стандартизации ради.

**Comment by EvilBeaver** [comment]
Мне самому название не нравится. Объявляю креативный конкурс на лучшее имя.

**Comment by nixel2007** [comment]
fs

**Comment by awa15** [comment]
f1s ))

**Comment by EvilBeaver** [comment]
#Использовать fs
    #Использовать fs-common

что симпатишнее?

**Comment by nixel2007** [comment]
симпатичнее - fs. правдивее - fs-common. :)

**Comment by awa15** [comment]
Имя библиотеки с дефисом - кошмар-кошмар. Например, Женя Сосна название моей программы Tool_1CD ни разу нигде не написал правильно, А виноват в этом не он, а я. Не фиг было вставлять никому не нужное подчеркивание. Поэтому только fs! Никаких fs-common.

**Comment by EvilBeaver** [comment]
Модно fscommon, но без дефиса не так сексуально выглядит. Название fs коррелирует с именем общего модуля ФС, который порождает эта библиотека.

**Comment by nixel2007** [comment]
В общем, fs :)
